version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment: 
      - DB=mysql://root:@tcp(sqldb:3306)/hr
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  sqldb:
    build: 
      context: .
      dockerfile: Dockerfile.mysql    
  redis:
    image: redis:6-alpine
