apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: employee-api2
description: employee-api22 delivery pipeline
serialPipeline:
 stages:
 - targetId: ist
 - targetId: uat
 - targetId: prod
