apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  namespace: employee
  labels:
    app: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: employee-api
          ports:
            - containerPort: 8080
