/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rcc.chatter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
//    @Test public void appHasAGreeting() {
//        Main classUnderTest = new Main();
//        assertNotNull("app should have a greeting", classUnderTest.main());
//    }
}
