apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: employee-api-cloud-run-service
profiles:
- name: ist
  manifests:
    rawYaml:
    - employee-ist.yaml
- name: uat
  manifests:
    rawYaml:
    - employee-uat.yaml
- name: prd
  manifests:
    rawYaml:
    - employee-prd.yaml
deploy:
  cloudrun: {}
